# NumPy Data Analysis Toolkit 📊

## Student Performance Analysis Project

**Author:** Tafadzwa Ben  
**Course:** Python for Data Science and Machine Learning Bootcamp  
**Section:** NumPy Fundamentals  

---

## Project Overview

This project demonstrates the use of NumPy for numerical data analysis.

The goal is to analyze student performance data by applying NumPy concepts such as:

- Creating and manipulating arrays
- Data indexing and slicing
- Mathematical operations
- Statistical analysis
- Aggregation functions
- Performance evaluation

---

## Objectives

By completing this project, I will demonstrate my ability to:

✅ Create NumPy arrays  
✅ Perform calculations using NumPy functions  
✅ Analyze datasets efficiently  
✅ Extract insights from numerical data  
✅ Apply NumPy in a real-world data analysis scenario  

---

## Dataset Description

The dataset contains student marks across different subjects:

- Python
- NumPy
- Statistics
- Data Analysis

The project will calculate:

- Total marks
- Average scores
- Class performance
- Highest-performing student
- Overall statistics

---

## Tools Used

- Python
- NumPy
- Jupyter Notebook

---

## Project Outcome

At the end of this project, I will have created a simple data analysis tool that demonstrates how NumPy can be used to transform raw numerical data into meaningful insights.

In [3]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.1


## Create Student Dataset

In [23]:
students = np.array([
    ["Tafadzwa",80,60,75],
    ["Gamu",78,85,86,],
    ["Masoka",87,74,85],
    ["Rumby",40,75,92]
])

students

array([['Tafadzwa', '80', '60', '75'],
       ['Gamu', '78', '85', '86'],
       ['Masoka', '87', '74', '85'],
       ['Rumby', '40', '75', '92']], dtype='<U21')

In [44]:
marks = students[:,1:].astype(float)

marks

array([[80., 60., 75.],
       [78., 85., 86.],
       [87., 74., 85.],
       [40., 75., 92.]])

In [47]:
total_marks = np.sum(marks)

total_marks

np.float64(917.0)

In [48]:
total_marks = np.sum(marks, axis =1)

total_marks

array([215., 249., 246., 207.])

In [26]:
average_marks = np.mean(marks,axis =1)

average_marks

array([71.66666667, 83.        , 82.        , 69.        ])

In [27]:
np.max(average_marks)

np.float64(83.0)

In [28]:
students[np.argmax(average_marks)]

array(['Gamu', '78', '85', '86'], dtype='<U21')

In [29]:
np.mean(average_marks)

np.float64(76.41666666666667)

In [30]:
np.median(average_marks)

np.float64(76.83333333333334)

In [31]:
np.std(average_marks)

np.float64(6.166103577895308)

## Performance Classification

In [40]:
for student, marks in zip(students[:,0], average_marks):

    if marks >=80:
        grade = "Excellent"
    elif marks >=65:
        grade = "Good"
    elif marks >=50:
        grade = "Pass"
    else:
        grade = "Failed"

    print("{} - {} ({:.2f})".format(student, grade, marks))

Tafadzwa - Good (71.67)
Gamu - Excellent (83.00)
Masoka - Excellent (82.00)
Rumby - Good (69.00)


## Find Class Average

In [79]:
print("=" * 50)
print("        STUDENT PERFORMANCE SUMMARY")
print("=" * 50)

print("Class Average: {:.2f}".format(class_average))
print("Highest Performer: {}".format(highest_student))
print("Highest Score: {:.2f}".format(highest_score))

print("-" * 50)

print("Performance Report")

for student, marks in zip(students[:,0], average_marks):

    if marks >=80:
        grade = "Excellent"
    elif marks >=65:
        grade = "Good"
    elif marks >=50:
        grade = "Pass"
    else:
        grade = "Failed"

    print("{} - {} ({:.2f})".format(student, grade, marks))

print("=" * 50)

        STUDENT PERFORMANCE SUMMARY
Class Average: 76.42
Highest Performer: Gamu
Highest Score: 83.00
--------------------------------------------------
Performance Report
Tafadzwa - Good (71.67)
Gamu - Excellent (83.00)
Masoka - Excellent (82.00)
Rumby - Good (69.00)


In [82]:
print("=" * 50)
print("        STUDENT PERFORMANCE SUMMARY")
print("=" * 50)
print("Class average: {:.2f}".format(class_average))
print("Highest Perfomer: {}".format(highest_student))
print("Highest Score: {}".format(np.max(average_marks)))
print("-" * 50)
print("Performance Report")

for student, marks in zip(students[:,0],average_marks):
    if marks >=75:
        grade = "Excellent"
    elif marks >=60:
        grade = "Good"
    elif marks >=50:
        grade = "Need Improvement"
    else :
        grade = "Work Hard"


    print("{} - {} ({:.2f})".format(student, grade, marks))

        STUDENT PERFORMANCE SUMMARY
Class average: 76.42
Highest Perfomer: Gamu
Highest Score: 83.0
--------------------------------------------------
Performance Report
Tafadzwa - Good (71.67)
Gamu - Excellent (83.00)
Masoka - Excellent (82.00)
Rumby - Good (69.00)
